# Generated by Django 5.2 on 2025-04-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_product_delete_article_delete_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название института"),
                ),
            ],
            options={
                "verbose_name": "Институт",
                "verbose_name_plural": "Институты",
            },
        ),
    ]
