# Generated by Django 5.2 on 2025-04-11 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_institute"),
    ]

    operations = [
        migrations.CreateModel(
            name="Head_of_the_educational_program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surname", models.CharField(max_length=30, verbose_name="Фамилия")),
                ("name", models.CharField(max_length=30, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(max_length=30, verbose_name="Отчество"),
                ),
                ("post", models.CharField(max_length=40, verbose_name="Должность")),
                (
                    "id_Institute",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.institute",
                        verbose_name="Институт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Руководитель образовательной программы",
                "verbose_name_plural": "Руководители образовательных программ",
            },
        ),
    ]
