# Generated by Django 5.2 on 2025-04-11 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id_department",
                    models.AutoField(
                        help_text="Уникальный идентификатор кафедры",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Выпускающей кафедры",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Полное название кафедры",
                        max_length=255,
                        verbose_name="Наименование выпускающей кафедры",
                    ),
                ),
                (
                    "id_institute",
                    models.ForeignKey(
                        help_text="Институт, к которому относится кафедра",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="myapp.institute",
                        verbose_name="ID Института",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выпускающая кафедра",
                "verbose_name_plural": "Выпускающие кафедры",
                "db_table": "departments",
                "ordering": ["name"],
            },
        ),
    ]
