# Generated by Django 5.2 on 2025-04-11 17:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationalProgram",
            fields=[
                (
                    "id_program",
                    models.AutoField(
                        help_text="Уникальный идентификатор программы",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Образовательной программы",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Полное название программы",
                        max_length=255,
                        verbose_name="Наименование образовательной программы",
                    ),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        help_text="Сокращенное название (например, ПМИ)",
                        max_length=20,
                        verbose_name="Аббревиатура программы",
                    ),
                ),
                (
                    "specialty_code",
                    models.CharField(
                        help_text="Код специальности по ФГОС",
                        max_length=15,
                        verbose_name="Шифр специальности",
                    ),
                ),
                (
                    "enrollment_year",
                    models.PositiveIntegerField(
                        help_text="Год первого набора студентов",
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2030),
                        ],
                        verbose_name="Год набора",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("development", "В разработке"),
                            ("accredited", "Аккредитована"),
                            ("expired", "Срок аккредитации истёк"),
                            ("suspended", "Приостановлена"),
                        ],
                        default="development",
                        help_text="Текущий статус программы",
                        max_length=15,
                        verbose_name="Статус программы",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        help_text="Кафедра, отвечающая за программу",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.department",
                        verbose_name="Выпускающая кафедра",
                    ),
                ),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        help_text="Руководитель образовательной программы",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.head_of_the_educational_program",
                        verbose_name="Руководитель программы",
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        blank=True,
                        help_text="Новость, связанная с программой",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.news",
                        verbose_name="Связанная новость",
                    ),
                ),
            ],
            options={
                "verbose_name": "Образовательная программа",
                "verbose_name_plural": "Образовательные программы",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("abbreviation", "enrollment_year"),
                        name="unique_program_per_year",
                    )
                ],
            },
        ),
    ]
