# Generated by Django 5.2 on 2025-04-11 17:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_educationalprogram"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="educationalprogram",
            options={
                "ordering": ["-enrollment_year", "name"],
                "verbose_name": "Образовательная программа",
                "verbose_name_plural": "Образовательные программы",
            },
        ),
        migrations.RemoveConstraint(
            model_name="educationalprogram",
            name="unique_program_per_year",
        ),
        migrations.RemoveField(
            model_name="educationalprogram",
            name="news",
        ),
        migrations.AlterField(
            model_name="educationalprogram",
            name="abbreviation",
            field=models.CharField(
                help_text="Сокращенное название (например, ПМИ)",
                max_length=20,
                verbose_name="Аббревиатура",
            ),
        ),
        migrations.AlterField(
            model_name="educationalprogram",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.department",
                verbose_name="Выпускающая кафедра",
            ),
        ),
        migrations.AlterField(
            model_name="educationalprogram",
            name="enrollment_year",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2030),
                ],
                verbose_name="Год набора",
            ),
        ),
        migrations.AlterField(
            model_name="educationalprogram",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.head_of_the_educational_program",
                verbose_name="Руководитель программы",
            ),
        ),
        migrations.AlterField(
            model_name="educationalprogram",
            name="id_program",
            field=models.AutoField(
                primary_key=True,
                serialize=False,
                verbose_name="ID Образовательной программы",
            ),
        ),
        migrations.AlterField(
            model_name="educationalprogram",
            name="name",
            field=models.CharField(
                help_text="Полное название образовательной программы",
                max_length=255,
                verbose_name="Наименование программы",
            ),
        ),
        migrations.AlterField(
            model_name="educationalprogram",
            name="status",
            field=models.CharField(
                choices=[("development", "сдана"), ("accredited", "не сдана")],
                default="development",
                max_length=15,
                verbose_name="Статус",
            ),
        ),
        migrations.AddConstraint(
            model_name="educationalprogram",
            constraint=models.UniqueConstraint(
                fields=("abbreviation", "enrollment_year"),
                name="unique_program_abbreviation_per_year",
            ),
        ),
    ]
