# Generated by Django 5.2 on 2025-04-11 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0011_matrix_delete_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matrix",
            name="add_date",
            field=models.DateField(
                auto_now_add=True, verbose_name="Дата добавления РОП"
            ),
        ),
        migrations.AlterField(
            model_name="matrix",
            name="assessment",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Неудовлетворительно"),
                    (2, "Удовлетворительно"),
                    (3, "Хорошо"),
                    (4, "Отлично"),
                    (5, "Превосходно"),
                ],
                null=True,
                verbose_name="Оценка",
            ),
        ),
        migrations.AlterField(
            model_name="matrix",
            name="check_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата проверки ОЛ"
            ),
        ),
        migrations.AlterField(
            model_name="matrix",
            name="comment",
            field=models.TextField(
                blank=True, max_length=1000, verbose_name="Комментарий ОЛ"
            ),
        ),
        migrations.AlterField(
            model_name="matrix",
            name="document_link",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="Ссылка на документ"
            ),
        ),
        migrations.AlterField(
            model_name="matrix",
            name="educational_program",
            field=models.ForeignKey(
                help_text="Выберите образовательную программу из списка",
                limit_choices_to={"status": "development"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matrices",
                to="myapp.educationalprogram",
                verbose_name="Образовательная программа",
            ),
        ),
        migrations.AlterField(
            model_name="matrix",
            name="id_matrix",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="ID Матрицы"
            ),
        ),
        migrations.AlterField(
            model_name="matrix",
            name="licensing_employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите сотрудника отдела лицензирования",
                limit_choices_to={"position__icontains": "лицензирования"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.employee",
                verbose_name="Сотрудник ОЛ",
            ),
        ),
        migrations.AlterModelTable(
            name="matrix",
            table=None,
        ),
    ]
