# Generated by Django 5.2 on 2025-04-11 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_alter_matrix_add_date_alter_matrix_assessment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matrix",
            name="licensing_employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите сотрудника отдела лицензирования",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="myapp.employee",
                verbose_name="Сотрудник ОЛ",
            ),
        ),
    ]
