# Generated by Django 5.2 on 2025-04-11 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_alter_matrix_assessment_passport"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scheme",
            fields=[
                (
                    "id_scheme",
                    models.AutoField(
                        help_text="Уникальный идентификатор схемы",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Схемы",
                    ),
                ),
                (
                    "creation_date",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Дата формирования схемы",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "approval_date",
                    models.DateField(
                        blank=True,
                        help_text="Дата утверждения схемы",
                        null=True,
                        verbose_name="Дата утверждения",
                    ),
                ),
                (
                    "document_link",
                    models.URLField(
                        blank=True,
                        help_text="Ссылка на схему в облачном хранилище",
                        max_length=500,
                        verbose_name="Ссылка на документ",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        help_text="Замечания по схеме",
                        max_length=2000,
                        verbose_name="Комментарии",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("approved", "Утверждена"),
                            ("rejected", "Отклонена"),
                        ],
                        default="draft",
                        help_text="Текущий статус схемы",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "educational_program",
                    models.ForeignKey(
                        help_text="Связанная образовательная программа",
                        limit_choices_to={"status": "development"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schemes",
                        to="myapp.educationalprogram",
                        verbose_name="Образовательная программа",
                    ),
                ),
                (
                    "responsible_employee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Сотрудник отдела лицензирования",
                        limit_choices_to={"position__icontains": "лицензирования"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="myapp.employee",
                        verbose_name="Ответственный сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Схема формирования компетенций",
                "verbose_name_plural": "Схемы формирования компетенций",
                "db_table": "schemes",
                "ordering": ["-creation_date"],
            },
        ),
    ]
