# Generated by Django 5.2 on 2025-04-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0016_alter_scheme_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheme",
            name="status",
            field=models.CharField(
                choices=[("сдана", "сдана"), ("не сдана", "не сдана")],
                default="draft",
                help_text="Текущий статус схемы",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
