# Generated by Django 5.2 on 2025-04-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0017_alter_scheme_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationalprogram",
            name="status",
            field=models.CharField(
                choices=[("сдана", "сдана"), ("не_сдана", "не_сдана")],
                default="development",
                max_length=15,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="assessment",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "сдан"), (2, "не_сдан")],
                null=True,
                verbose_name="Оценка",
            ),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="status",
            field=models.CharField(
                choices=[("сдана", "сдана"), ("не_сдана", "не_сдана")],
                default="draft",
                help_text="Текущий статус схемы",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
