# Generated by Django 5.1.5 on 2025-05-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_alter_educationalprogram_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон для матрицы",
                "verbose_name_plural": "Шаблоны для матрицы",
            },
        ),
    ]
