# Generated by Django 5.2 on 2025-06-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0020_delete_shm"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="passport",
            options={
                "ordering": ["-add_date"],
                "verbose_name": "Паспорт ОП",
                "verbose_name_plural": "Паспорта ОП",
            },
        ),
        migrations.RemoveField(
            model_name="passport",
            name="check_date",
        ),
        migrations.RemoveField(
            model_name="passport",
            name="comment",
        ),
        migrations.AlterField(
            model_name="passport",
            name="assessment",
            field=models.IntegerField(
                choices=[(1, "сдан"), (2, "не_сдан")],
                default=2,
                verbose_name="Статус проверки",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="document_link",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="passports/",
                verbose_name="Файл документа",
            ),
        ),
    ]
