# Generated by Django 5.2 on 2025-06-04 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0021_alter_passport_options_remove_passport_check_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matrix",
            name="educational_program",
            field=models.ForeignKey(
                help_text="Выберите образовательную программу из списка",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matrices",
                to="myapp.educationalprogram",
                verbose_name="Образовательная программа",
            ),
        ),
        migrations.AlterField(
            model_name="passport",
            name="educational_program",
            field=models.ForeignKey(
                help_text="Выберите образовательную программу из списка",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passports",
                to="myapp.educationalprogram",
                verbose_name="Образовательная программа",
            ),
        ),
        migrations.AlterField(
            model_name="scheme",
            name="educational_program",
            field=models.ForeignKey(
                help_text="Выберите образовательную программу из списка",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schemes",
                to="myapp.educationalprogram",
                verbose_name="Образовательная программа",
            ),
        ),
    ]
